// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/course": {
            "get": {
                "description": "获取课程 可以自由添加筛选属性",
                "tags": [
                    "course"
                ],
                "summary": "获取课程",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 4,
                        "description": "学分",
                        "name": "credit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "院系号",
                        "name": "department_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "数据库原理",
                        "description": "课名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "0121",
                        "description": "课号",
                        "name": "number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "创建课程",
                "tags": [
                    "course"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "description": "course 实例",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/course/{id}": {
            "get": {
                "description": "根据id获取课程信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "根据id获取课程信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                }
            },
            "put": {
                "description": "整体更新课程信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "整体更新课程信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "course 实例",
                        "name": "course",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login/admin": {
            "post": {
                "description": "以管理员身份登录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "以管理员身份登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/login/student": {
            "post": {
                "description": "以学生身份登录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "以学生身份登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "学号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Student"
                        }
                    }
                }
            }
        },
        "/login/teacher": {
            "post": {
                "description": "以教师身份登录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "以教师身份登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/selection": {
            "post": {
                "description": "创建选课",
                "tags": [
                    "selection"
                ],
                "summary": "创建选课",
                "parameters": [
                    {
                        "description": "选课情况",
                        "name": "selection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Selection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除选课",
                "tags": [
                    "selection"
                ],
                "summary": "删除选课",
                "parameters": [
                    {
                        "description": "选课情况",
                        "name": "selection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Selection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student": {
            "get": {
                "description": "获取所有学生信息",
                "tags": [
                    "student"
                ],
                "summary": "获取所有学生信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StudentRes"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建学生",
                "tags": [
                    "student"
                ],
                "summary": "创建学生",
                "parameters": [
                    {
                        "description": "student 实例",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StudentCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/{id}": {
            "get": {
                "description": "根据id获取学生信息",
                "tags": [
                    "student"
                ],
                "summary": "根据id获取学生信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.StudentRes"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据id删除学生",
                "tags": [
                    "student"
                ],
                "summary": "根据id删除学生",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/{id}/course": {
            "get": {
                "description": "获取指定学生的所有课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "student",
                    "course"
                ],
                "summary": "获取指定学生的所有课程",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否有成绩 不写即全部返回",
                        "name": "hasScore",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.OfferedCourseRes"
                            }
                        }
                    }
                }
            }
        },
        "/student/{student_id}/course/{course_id}": {
            "put": {
                "description": "更新课程成绩",
                "tags": [
                    "selection",
                    "admin"
                ],
                "summary": "更新课程成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "course ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "score",
                        "name": "score",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/generate-examples": {
            "get": {
                "description": "生成样例数据",
                "tags": [
                    "test"
                ],
                "summary": "生成样例数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/ping": {
            "get": {
                "description": "pong me!",
                "tags": [
                    "test"
                ],
                "summary": "ping!",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Course": {
            "type": "object",
            "properties": {
                "credit": {
                    "description": "学分",
                    "type": "integer",
                    "example": 4
                },
                "department_id": {
                    "description": "院系号",
                    "type": "integer"
                },
                "name": {
                    "description": "课名",
                    "type": "string",
                    "example": "数据库原理"
                },
                "number": {
                    "description": "课号",
                    "type": "string",
                    "example": "0121"
                }
            }
        },
        "model.OfferedCourse": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "课号",
                    "type": "integer"
                },
                "selections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Selection"
                    }
                },
                "teacher_id": {
                    "description": "教师工号",
                    "type": "integer"
                },
                "term": {
                    "description": "学期",
                    "type": "string",
                    "example": "22-冬季学期"
                }
            }
        },
        "model.OfferedCourseRes": {
            "type": "object",
            "properties": {
                "credit": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "student_name": {
                    "type": "string"
                },
                "teacher_name": {
                    "type": "string"
                },
                "term": {
                    "type": "string"
                }
            }
        },
        "model.Selection": {
            "type": "object",
            "properties": {
                "offeredCourse": {
                    "type": "object",
                    "$ref": "#/definitions/model.OfferedCourse"
                },
                "offeredCourseID": {
                    "type": "integer"
                },
                "score": {
                    "description": "分数, -1表示未评分",
                    "type": "integer",
                    "example": 75
                },
                "student": {
                    "type": "object",
                    "$ref": "#/definitions/model.Student"
                },
                "studentID": {
                    "type": "integer"
                }
            }
        },
        "model.Student": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "departmentID": {
                    "description": "所属院系号",
                    "type": "integer"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "number": {
                    "description": "学号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123"
                },
                "selections": {
                    "description": "选课情况",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Selection"
                    }
                },
                "sex": {
                    "description": "性别",
                    "type": "string"
                }
            }
        },
        "model.StudentCreateReq": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                }
            }
        },
        "model.StudentRes": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "department_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "description": "ID uint ` + "`" + `json:\"id\"` + "`" + `",
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Academic System",
	Description: "教务管理系统",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
